service:
    name: 'seed-example'
    port: 2220
environment:
    name: 'default'
    production: false
    node_env:
database:
    type: 'mongodb'
    host:
    port:
    database:
    username:
    password:
    synchronize: true
sonarqube:
    host:
    port:
    version:
